### PR TITLE
Update to angular 10

### PR DESCRIPTION
**Pull request by bulldog98**
Update angular to 10.0 and rxjs to 6.6.0

### CODE REVIEW

**Comment by nilsmehlhorn** [comment]
Thanks for the contribution!  :raised_hands: 

It looks good to me, one thing though, I'm bumping the version in `projects/ngx-pagination-data-source/package.json`, so I'd say it doesn't need to be tracked in the main one, but doesn't really matter.

Could you rebase upon the master in order to have the CI running? I fixed it with #3

**Comment by bulldog98** [comment]
I'm happy to contribute. I saw your comment at work, but had no way to rebase then.

**Comment by bulldog98** [comment]
Sorry for the multiple force pushes, I was just trying to get the conventional-commit to not complain :)

**Comment by nilsmehlhorn** [comment]
It's force-pushed to your repository, so I don't really mind. Actually, I thought that conventional-commit will only check the latest commit, but anyway, great that you've fixed that, thanks very much!

**Pull request merged**
